from pathlib import Path
from .base import ThemeProvider
import shutil
import os

class FootProvider(ThemeProvider):
    @property
    def name(self) -> str:
        return "Foot Terminal"

    def get_config_path(self) -> Path:
        return Path.home() / ".config/foot/theme.ini"

    def get_main_config_path(self) -> Path:
        return Path.home() / ".config/foot/foot.ini"

    def generate_content(self, data: dict) -> str:
        p = data.get('palette', {})
        ui = data.get('ui', {})
        
        # Helper to strip hash
        def no_hash(color):
            return color.lstrip('#') if color else "000000"

        lines = [
            f"# Generated by Chameleon for theme: {data.get('meta', {}).get('name')}",
            "[colors]",
            f"background={no_hash(ui.get('background', p.get('c00_black')))}",
            f"foreground={no_hash(ui.get('foreground', p.get('c07_white')))}",
            "",
            "# Regular Colors",
            f"regular0={no_hash(p.get('c00_black'))}",
            f"regular1={no_hash(p.get('c01_red'))}",
            f"regular2={no_hash(p.get('c02_green'))}",
            f"regular3={no_hash(p.get('c03_yellow'))}",
            f"regular4={no_hash(p.get('c04_blue'))}",
            f"regular5={no_hash(p.get('c05_violet'))}",
            f"regular6={no_hash(p.get('c06_cyan'))}",
            f"regular7={no_hash(p.get('c07_white'))}",
            "",
            "# Bright Colors",
            f"bright0={no_hash(p.get('c08_br_black'))}",
            f"bright1={no_hash(p.get('c09_br_red'))}",
            f"bright2={no_hash(p.get('c10_br_green'))}",
            f"bright3={no_hash(p.get('c11_br_yellow'))}",
            f"bright4={no_hash(p.get('c12_br_blue'))}",
            f"bright5={no_hash(p.get('c13_br_violet'))}",
            f"bright6={no_hash(p.get('c14_br_cyan'))}",
            f"bright7={no_hash(p.get('c15_br_white'))}",
        ]
        return "\n".join(lines)

    @property
    def include_format(self) -> str:
        return "include={path}"

    def check_integration(self):
        """
        Specialized integration check for Foot.
        Foot requires 'include=' to be at the top level (global), preferably at the start of the file.
        Appending it to the end often puts it inside a [section], which causes errors.
        """
        if self.dry_run: return

        main_conf = self.get_main_config_path()
        theme_conf = self.get_config_path()

        if not main_conf.exists():
            return

        # Check if already included
        with open(main_conf, 'r') as f:
            if str(theme_conf) in f.read() or theme_conf.name in f.read():
                return

        # Not found, ask user
        print(f"⚠️  [{self.name}] Theme file is NOT included in {main_conf.name}.")
        print(f"   Required line: {self.include_format.format(path=theme_conf)}")
        print(f"   (Note: This will be added to the TOP of the file)")
        
        try:
            choice = input(f"   >> Prepend this line automatically? [y/N] ").strip().lower()
        except EOFError:
            choice = 'n'
        
        if choice == 'y':
            try:
                with open(main_conf, 'r') as f:
                    original_content = f.read()
                
                with open(main_conf, 'w') as f:
                    f.write(f"# Chameleon Theme Integration\n")
                    f.write(self.include_format.format(path=theme_conf) + "\n")
                    f.write(original_content)
                
                print(f"   ✅ Prepended include to {main_conf.name}")
            except Exception as e:
                print(f"   ❌ Error modifying file: {e}")
        else:
            print(f"   ℹ️  Skipping auto-integration.")