from pathlib import Path
from .base import ThemeProvider
import shutil
import os

class FootProvider(ThemeProvider):
    @property
    def name(self) -> str:
        return "Foot Terminal"

    def get_config_path(self) -> Path:
        return Path.home() / ".config/foot/theme.ini"

    def get_main_config_path(self) -> Path:
        return Path.home() / ".config/foot/foot.ini"

    @property
    def include_format(self) -> str:
        return "include={path}"

    def generate_content(self, data: dict) -> str:
        p = data.get('palette', {})
        ui = data.get('ui', {})
        
        # Helper to strip hash
        def no_hash(color):
            return color.lstrip('#') if color else "000000"

        lines = [
            f"# Generated by Chameleon for theme: {data.get('meta', {}).get('name')}",
            "[colors]",
            f"background={no_hash(ui.get('background', p.get('c00_black')))}",
            f"foreground={no_hash(ui.get('foreground', p.get('c07_white')))}",
            "",
            "# Regular Colors",
            f"regular0={no_hash(p.get('c00_black'))}",
            f"regular1={no_hash(p.get('c01_red'))}",
            f"regular2={no_hash(p.get('c02_green'))}",
            f"regular3={no_hash(p.get('c03_yellow'))}",
            f"regular4={no_hash(p.get('c04_blue'))}",
            f"regular5={no_hash(p.get('c05_violet'))}",
            f"regular6={no_hash(p.get('c06_cyan'))}",
            f"regular7={no_hash(p.get('c07_white'))}",
            "",
            "# Bright Colors",
            f"bright0={no_hash(p.get('c08_br_black'))}",
            f"bright1={no_hash(p.get('c09_br_red'))}",
            f"bright2={no_hash(p.get('c10_br_green'))}",
            f"bright3={no_hash(p.get('c11_br_yellow'))}",
            f"bright4={no_hash(p.get('c12_br_blue'))}",
            f"bright5={no_hash(p.get('c13_br_violet'))}",
            f"bright6={no_hash(p.get('c14_br_cyan'))}",
            f"bright7={no_hash(p.get('c15_br_white'))}",
        ]
        return "\n".join(lines)
