from pathlib import Path
from .base import ThemeProvider
import shutil

class GtkProvider(ThemeProvider):
    @property
    def name(self) -> str:
        return "GTK 3/4"

    def is_available(self) -> bool:
        # Check if GTK config dirs exist
        gtk3 = Path.home() / ".config/gtk-3.0"
        gtk4 = Path.home() / ".config/gtk-4.0"
        return gtk3.exists() or gtk4.exists()

    def get_config_path(self) -> Path:
        # Main target is GTK 3, but we'll try to write to both in apply()
        return Path.home() / ".config/gtk-3.0/gtk.css"

    def get_main_config_path(self) -> Path:
        # GTK doesn't have a single "main" config to include into, 
        # gtk.css IS the override file.
        return Path.home() / ".config/gtk-3.0/settings.ini"

    def generate_content(self, data: dict) -> str:
        ui = data.get('ui', {})
        p = data.get('palette', {})
        
        # Mapping: Use the "Theme Accent" (c05 or c10 depending on theme logic)
        # For Green Hill/Monored remaster, we want the Neon color.
        # Let's use c10_br_green (which we mapped to the main Neon color in both themes)
        # or c05_violet (which is the classic accent slot).
        
        # Let's use the 'foreground' from UI as the main accent text, 
        # and a slightly dimmed version for backgrounds if possible, 
        # but GTK CSS needs specific overrides.
        
        accent = p.get('c10_br_green', '#55FF55') 
        bg = ui.get('background', '#000000')
        fg = ui.get('foreground', '#ffffff')
        sel = ui.get('selection', '#333333')

        css = [
            f"/* Generated by Chameleon for theme: {data.get('meta', {}).get('name')} */",
            "",
            # GTK Standard Colors overrides
            f"@define-color theme_selected_bg_color {accent}",
            f"@define-color theme_selected_fg_color {bg}",
            f"@define-color selection_color {accent}",
            f"@define-color theme_bg_color {bg}",
            f"@define-color theme_fg_color {fg}",
            f"@define-color theme_base_color {bg}",
            f"@define-color theme_text_color {fg}",
            "",
            # Specific Widgets
            "entry, view, text {",
            f"  background-color: {bg}",
            f"  color: {fg}",
            "}",
            "",
            "entry:selected, entry selection {",
            f"  background-color: {accent}",
            f"  color: {bg}",
            "}",
            "",
            "button {",
            f"  border-color: {sel}",
            "}",
            "",
            "/* Link Colors */",
            f"@define-color link_color {accent}",
            f"@define-color link_visited_color {p.get('c13_br_violet', accent)}"
        ]
        return "\n".join(css)

    def apply(self, theme_data: dict):
        # Override apply to write to both GTK 3 and GTK 4
        content = self.generate_content(theme_data)
        
        targets = [
            Path.home() / ".config/gtk-3.0/gtk.css",
            Path.home() / ".config/gtk-4.0/gtk.css"
        ]

        print(f"[{self.name}] Generating GTK CSS...")
        
        if self.dry_run:
            print(content)
            return

        for target in targets:
            if target.parent.exists():
                try:
                    with open(target, 'w') as f:
                        f.write(content)
                    print(f"[{self.name}] Wrote to {target}")
                except Exception as e:
                    print(f"[{self.name}] Error writing to {target}: {e}")
            else:
                print(f"[{self.name}] Skipping {target} (Directory not found)")
        
        # GTK apps usually reload CSS instantly or on restart. 
        # We can try to reload GSettings to force a refresh if needed.
