from pathlib import Path
from .base import ThemeProvider
import os
import shutil

class HyprlandProvider(ThemeProvider):
    @property
    def name(self) -> str:
        return "Hyprland"

    def get_config_path(self) -> Path:
        return Path.home() / ".config/hypr/myColors.conf"

    def get_main_config_path(self) -> Path:
        return Path.home() / ".config/hypr/hyprland.conf"

    @property
    def include_format(self) -> str:
        return "source = {path}"

    def is_available(self) -> bool:
        # Check for hyprctl binary instead of Hyprland process for better reliability
        return shutil.which("hyprctl") is not None

    def hex_to_rgb(self, hex_color):
        """Converts #RRGGBB to rgb(rrggbb) format for Hyprland."""
        if not hex_color:
            return "rgb(000000)"
        clean_hex = hex_color.lstrip('#')
        return f"rgb({clean_hex})"

    def generate_content(self, data: dict) -> str:
        p = data.get('palette', {})
        ui = data.get('ui', {})
        
        # Fallbacks provided for safety
        lines = [
            f"# Generated by Chameleon for theme: {data.get('meta', {}).get('name', 'Unknown')}",
            "",
            "# UI Elements",
            f"$background = {self.hex_to_rgb(ui.get('background', p.get('c00_black')))}",
            f"$foreground = {self.hex_to_rgb(ui.get('foreground', p.get('c07_white')))}",
            f"$ui_active = {self.hex_to_rgb(ui.get('border', p.get('c05_violet')))}",
            f"$ui_border = {self.hex_to_rgb(p.get('c08_br_black', '#333333'))}",
            "",
            "# ANSI Palette Mapped to Variables",
            f"$c0 = {self.hex_to_rgb(p.get('c00_black', '#000000'))}",
            f"$c1 = {self.hex_to_rgb(p.get('c01_red', '#ff0000'))}",
            f"$c2 = {self.hex_to_rgb(p.get('c02_green', '#00ff00'))}",
            f"$c3 = {self.hex_to_rgb(p.get('c03_yellow', '#ffff00'))}",
            f"$c4 = {self.hex_to_rgb(p.get('c04_blue', '#0000ff'))}",
            f"$c5 = {self.hex_to_rgb(p.get('c05_violet', '#ff00ff'))}",
            f"$c6 = {self.hex_to_rgb(p.get('c06_cyan', '#00ffff'))}",
            f"$c7 = {self.hex_to_rgb(p.get('c07_white', '#ffffff'))}",
            f"$c8 = {self.hex_to_rgb(p.get('c08_br_black', '#444444'))}",
            f"$c9 = {self.hex_to_rgb(p.get('c09_br_red', '#ff5555'))}",
            f"$c10 = {self.hex_to_rgb(p.get('c10_br_green', '#55ff55'))}",
            f"$c11 = {self.hex_to_rgb(p.get('c11_br_yellow', '#ffff55'))}",
            f"$c12 = {self.hex_to_rgb(p.get('c12_br_blue', '#5555ff'))}",
            f"$c13 = {self.hex_to_rgb(p.get('c13_br_violet', '#ff55ff'))}",
            f"$c14 = {self.hex_to_rgb(p.get('c14_br_cyan', '#55ffff'))}",
            f"$c15 = {self.hex_to_rgb(p.get('c15_br_white', '#ffffff'))}",
        ]
        
        return "\n".join(lines)

    def reload(self):
        if self.is_available():
            # Use quiet flag or redirect output if needed
            # os.system("hyprctl reload > /dev/null 2>&1")
            print("[Hyprland] Reloading via hyprctl...")
            os.system("hyprctl reload")
