from pathlib import Path
import shutil
from .base import ThemeProvider

class NeovimProvider(ThemeProvider):
    @property
    def name(self) -> str:
        return "Neovim"
    
    def is_available(self) -> bool:
        return shutil.which("nvim") is not None

    def get_config_path(self) -> Path:
        # Saves to a Lua file that Neovim will require
        return Path.home() / ".config/nvim/lua/current_theme.lua"

    def get_main_config_path(self) -> Path:
        # We check if init.lua exists to confirm availability
        return Path.home() / ".config/nvim/init.lua"

    @property
    def include_format(self) -> str:
        # This is informational; Neovim requires explicit 'require' in init.lua
        return 'require("current_theme")'

    def check_integration(self):
        # Override to check for module name without extension
        if self.dry_run: return
        
        main_conf = self.get_main_config_path()
        if not main_conf.exists(): return
        
        with open(main_conf, 'r') as f:
            content = f.read()
            # Lua requires modules without extension
            if "current_theme" in content:
                # Silent success or debug log
                return
        
        # If not found, fall back to base behavior (which will prompt)
        super().check_integration()

    def generate_content(self, data: dict) -> str:
        # We will generate a Lua file that sets the colorscheme.
        # Ideally, we should pass the theme name so Neovim loads the installed colorscheme.
        
        theme_name = data.get('meta', {}).get('name', 'sanxz4').lower().replace(" ", "")
        
        # Mapping known YAML names to Neovim colorscheme names if they differ
        # For now, assuming direct mapping: "Green Hill" -> "greenhill"
        
        lines = [
            f"-- Generated by Chameleon for theme: {data.get('meta', {}).get('name')}",
            "-- Require this file in your init.lua: require('current_theme')",
            "",
            f'vim.cmd.colorscheme("{theme_name}")', 
            "",
            "-- Optional: Inject global variables if your theme uses them",
            f'vim.g.chameleon_theme = "{theme_name}"'
        ]
        return "\n".join(lines)
