from pathlib import Path
from .base import ThemeProvider
import subprocess
import shutil

class WaybarProvider(ThemeProvider):
    @property
    def name(self) -> str:
        return "Waybar"

    def get_config_path(self) -> Path:
        return Path.home() / ".config/waybar/colors.css"

    def get_main_config_path(self) -> Path:
        return Path.home() / ".config/waybar/style.css"

    @property
    def include_format(self) -> str:
        return "@import '{path}';"

    def is_available(self) -> bool:
        return shutil.which("waybar") is not None

    def generate_content(self, data: dict) -> str:
        p = data.get('palette', {})
        ui = data.get('ui', {})
        meta = data.get('meta', {})

        lines = [
            f"/* Generated by Chameleon for theme: {meta.get('name', 'Unknown')} */",
            "",
            "/* UI Colors */",
            f"@define-color background {ui.get('background', '#000000')};",
            f"@define-color foreground {ui.get('foreground', '#ffffff')};",
            f"@define-color border {ui.get('border', '#333333')};",
            f"@define-color selection {ui.get('selection', '#444444')};",
            "",
            "/* Palette */",
            f"@define-color c00_black {p.get('c00_black', '#000000')};",
            f"@define-color c01_red {p.get('c01_red', '#ff0000')};",
            f"@define-color c02_green {p.get('c02_green', '#00ff00')};",
            f"@define-color c03_yellow {p.get('c03_yellow', '#ffff00')};",
            f"@define-color c04_blue {p.get('c04_blue', '#0000ff')};",
            f"@define-color c05_violet {p.get('c05_violet', '#ff00ff')};",
            f"@define-color c06_cyan {p.get('c06_cyan', '#00ffff')};",
            f"@define-color c07_white {p.get('c07_white', '#ffffff')};",
            f"@define-color c08_br_black {p.get('c08_br_black', '#444444')};",
            f"@define-color c09_br_red {p.get('c09_br_red', '#ff5555')};",
            f"@define-color c10_br_green {p.get('c10_br_green', '#55ff55')};",
            f"@define-color c11_br_yellow {p.get('c11_br_yellow', '#ffff55')};",
            f"@define-color c12_br_blue {p.get('c12_br_blue', '#5555ff')};",
            f"@define-color c13_br_violet {p.get('c13_br_violet', '#ff55ff')};",
            f"@define-color c14_br_cyan {p.get('c14_br_cyan', '#55ffff')};",
            f"@define-color c15_br_white {p.get('c15_br_white', '#ffffff')};",
        ]
        return "\n".join(lines)

    def check_integration(self):
        """
        Specialized integration check for Waybar.
        Waybar (GTK CSS) requires '@import' to be at the TOP level, 
        preferably at the very start of the file.
        """
        if self.dry_run: return

        main_conf = self.get_main_config_path()
        theme_conf = self.get_config_path()

        if not main_conf.exists():
            return

        # Check if already included
        with open(main_conf, 'r') as f:
            if str(theme_conf) in f.read() or theme_conf.name in f.read():
                return

        # Not found, ask user
        print(f"⚠️  [{self.name}] Theme file is NOT included in {main_conf.name}.")
        print(f"   Required line: {self.include_format.format(path=theme_conf)}")
        print(f"   (Note: This will be added to the TOP of the file)")
        
        try:
            choice = input(f"   >> Prepend this line automatically? [y/N] ").strip().lower()
        except EOFError:
            choice = 'n'
        
        if choice == 'y':
            try:
                with open(main_conf, 'r') as f:
                    original_content = f.read()
                
                with open(main_conf, 'w') as f:
                    f.write(f"/* Chameleon Theme Integration */\n")
                    f.write(self.include_format.format(path=theme_conf) + "\n")
                    f.write(original_content)
                
                print(f"   ✅ Prepended include to {main_conf.name}")
            except Exception as e:
                print(f"   ❌ Error modifying file: {e}")
        else:
            print(f"   ℹ️  Skipping auto-integration.")

    def reload(self):
        if self.is_available():
            print("[Waybar] Reloading CSS...")
            try:
                # SIGUSR2 reloads style.css
                subprocess.run(["pkill", "-SIGUSR2", "waybar"], check=False)
            except Exception as e:
                print(f"❌ [Waybar] Failed to send reload signal: {e}")
