from pathlib import Path
from .base import ThemeProvider
import shutil

class WofiProvider(ThemeProvider):
    @property
    def name(self) -> str:
        return "Wofi"

    def is_available(self) -> bool:
        return shutil.which("wofi") is not None

    def get_config_path(self) -> Path:
        return Path.home() / ".config/wofi/colors.css"

    def get_main_config_path(self) -> Path:
        return Path.home() / ".config/wofi/style.css"

    @property
    def include_format(self) -> str:
        return "@import '{path}';"

    def generate_content(self, data: dict) -> str:
        p = data.get('palette', {})
        ui = data.get('ui', {})
        
        # GTK CSS syntax for color definitions
        lines = [
            f"/* Generated by Chameleon for theme: {data.get('meta', {}).get('name')} */",
            "",
            f"@define-color background {ui.get('background', '#000000')};",
            f"@define-color foreground {ui.get('foreground', '#ffffff')};",
            f"@define-color border {ui.get('border', '#333333')};",
            f"@define-color selection {ui.get('selection', '#222222')};",
            "",
            f"@define-color c00_black {p.get('c00_black')};",
            f"@define-color c01_red {p.get('c01_red')};",
            f"@define-color c02_green {p.get('c02_green')};",
            f"@define-color c03_yellow {p.get('c03_yellow')};",
            f"@define-color c04_blue {p.get('c04_blue')};",
            f"@define-color c05_violet {p.get('c05_violet')};",
            f"@define-color c06_cyan {p.get('c06_cyan')};",
            f"@define-color c07_white {p.get('c07_white')};",
            "",
            f"@define-color c08_br_black {p.get('c08_br_black')};",
            f"@define-color c09_br_red {p.get('c09_br_red')};",
            f"@define-color c10_br_green {p.get('c10_br_green')};",
            f"@define-color c11_br_yellow {p.get('c11_br_yellow')};",
            f"@define-color c12_br_blue {p.get('c12_br_blue')};",
            f"@define-color c13_br_violet {p.get('c13_br_violet')};",
            f"@define-color c14_br_cyan {p.get('c14_br_cyan')};",
            f"@define-color c15_br_white {p.get('c15_br_white')};"
        ]
        return "\n".join(lines)

    def reload(self):
        # Wofi doesn't have a reload signal, usually restarts on launch.
        # But we can try to kill it if it's running residently (rare for wofi).
        pass
