from pathlib import Path
from .base import ThemeProvider
from utils.colors import hex_to_rgb_semicolon

class ZshProvider(ThemeProvider):
    @property
    def name(self) -> str:
        return "Zsh Shell"

    def get_config_path(self) -> Path:
        # Saves to the file sourced by .zshrc
        return Path.home() / "resources/custom/colors.zsh"

    def get_main_config_path(self) -> Path:
        return Path.home() / ".zshrc"

    @property
    def include_format(self) -> str:
        return "source {path}"
    
    def generate_content(self, data: dict) -> str:
        p = data.get('palette', {})
        ui = data.get('ui', {})
        
        # 1. Export standard ENV variables for Scripts/Prompt
        lines = [
            f"# Generated by Chameleon for theme: {data.get('meta', {}).get('name')}",
            "# Source this file in your .zshrc",
            "",
            "# UI Colors",
            f"export COLOR_BACKGROUND='{ui.get('background', '')}'",
            f"export COLOR_FOREGROUND='{ui.get('foreground', '')}'",
            "",
            "# Palette Variables",
            f"export c00_black='{p.get('c00_black', '')}'",
            f"export c01_red='{p.get('c01_red', '')}'",
            f"export c02_green='{p.get('c02_green', '')}'",
            f"export c03_yellow='{p.get('c03_yellow', '')}'",
            f"export c04_blue='{p.get('c04_blue', '')}'",
            f"export c05_violet='{p.get('c05_violet', '')}'",
            f"export c06_cyan='{p.get('c06_cyan', '')}'",
            f"export c07_white='{p.get('c07_white', '')}'",
            f"export c08_br_black='{p.get('c08_br_black', '')}'",
            f"export c09_br_red='{p.get('c09_br_red', '')}'",
            f"export c10_br_green='{p.get('c10_br_green', '')}'",
            f"export c11_br_yellow='{p.get('c11_br_yellow', '')}'",
            f"export c12_br_blue='{p.get('c12_br_blue', '')}'",
            f"export c13_br_violet='{p.get('c13_br_violet', '')}'",
            f"export c14_br_cyan='{p.get('c14_br_cyan', '')}'",
            f"export c15_br_white='{p.get('c15_br_white', '')}'",
            "",
            "# --- LS_COLORS Dynamic Generation ---",
            "# Automatically maps palette colors to file types",
            ""
        ]
        
        # 2. Generate Dynamic LS_COLORS
        # Mapping Logic:
        # Directory -> c04 (Blue) or Theme Accent? -> Let's use c04 (Blue) as standard dir, or c05 (Violet) for theme?
        # Let's stick to Semantic Mapping from the YAML if available, or fall back to ANSI logic.
        
        c_dir = hex_to_rgb_semicolon(p.get('c04_blue'))      # Folder = Blue
        c_exec = hex_to_rgb_semicolon(p.get('c02_green'))    # Exec = Green
        c_zip = hex_to_rgb_semicolon(p.get('c01_red'))       # Zip = Red
        c_link = hex_to_rgb_semicolon(p.get('c06_cyan'))     # Link = Cyan
        c_media = hex_to_rgb_semicolon(p.get('c05_violet'))  # Media = Violet
        c_doc = hex_to_rgb_semicolon(p.get('c07_white'))     # Text = White
        c_code = hex_to_rgb_semicolon(p.get('c06_cyan'))     # Code = Cyan

        ls_lines = [
            f"export LS_COLORS=\"di=1;38;2;{c_dir}:\"  # Directory",
            f"LS_COLORS+=\"ln=38;2;{c_link}:\"         # Symlink",
            f"LS_COLORS+=\"ex=1;38;2;{c_exec}:\"       # Executable",
            f"LS_COLORS+=\"*.zip=38;2;{c_zip}:*.tar=38;2;{c_zip}:*.gz=38;2;{c_zip}:\" # Archives",
            f"LS_COLORS+=\"*.jpg=38;2;{c_media}:*.png=38;2;{c_media}:*.mp4=38;2;{c_media}:*.mp3=38;2;{c_media}:\" # Media",
            f"LS_COLORS+=\"*.py=38;2;{c_code}:*.js=38;2;{c_code}:*.c=38;2;{c_code}:\" # Code",
            f"LS_COLORS+=\"*.txt=38;2;{c_doc}:*.md=38;2;{c_doc}:*.cfg=38;2;{c_doc}:\" # Docs",
            "",
            "# Apply to Zsh completion",
            "zstyle ':completion:*' list-colors \"${(s.:.)LS_COLORS}\""
        ]
        
        lines.extend(ls_lines)
        return "\n".join(lines)