from pathlib import Path
from .base import ThemeProvider

class ZshProvider(ThemeProvider):
    @property
    def name(self) -> str:
        return "Zsh Shell"

    def get_config_path(self) -> Path:
        # Saves to the file sourced by .zshrc
        return Path.home() / "resources/custom/colors.zsh"

    def get_main_config_path(self) -> Path:
        return Path.home() / ".zshrc"

    @property
    def include_format(self) -> str:
        return "source {path}"

    def generate_content(self, data: dict) -> str:
        p = data.get('palette', {})
        ui = data.get('ui', {})
        
        lines = [
            f"# Generated by Chameleon for theme: {data.get('meta', {}).get('name')}",
            "# Source this file in your .zshrc",
            "",
            "# UI Colors",
            f"export COLOR_BACKGROUND='{ui.get('background', '')}'",
            f"export COLOR_FOREGROUND='{ui.get('foreground', '')}'",
            "",
            "# Palette Variables (Matching your existing naming convention if possible)",
            f"export c00_black='{p.get('c00_black', '')}'",
            f"export c01_red='{p.get('c01_red', '')}'",
            f"export c02_green='{p.get('c02_green', '')}'",
            f"export c03_yellow='{p.get('c03_yellow', '')}'",
            f"export c04_blue='{p.get('c04_blue', '')}'",
            f"export c05_violet='{p.get('c05_violet', '')}'",
            f"export c06_cyan='{p.get('c06_cyan', '')}'",
            f"export c07_white='{p.get('c07_white', '')}'",
            f"export c08_br_black='{p.get('c08_br_black', '')}'",
            f"export c09_br_red='{p.get('c09_br_red', '')}'",
            f"export c10_br_green='{p.get('c10_br_green', '')}'",
            f"export c11_br_yellow='{p.get('c11_br_yellow', '')}'",
            f"export c12_br_blue='{p.get('c12_br_blue', '')}'",
            f"export c13_br_violet='{p.get('c13_br_violet', '')}'",
            f"export c14_br_cyan='{p.get('c14_br_cyan', '')}'",
            f"export c15_br_white='{p.get('c15_br_white', '')}'",
        ]
        return "\n".join(lines)
