-- Generated by Chameleon for theme: SANXZ Warm/Cool
-- Require this file in your init.lua: require('current_theme')

vim.cmd.colorscheme("sanxzwarm/cool")

-- Optional: Inject global variables if your theme uses them
vim.g.chameleon_theme = "sanxzwarm/cool"