-- Generated by Chameleon for theme: Green Hill
-- Require this file in your init.lua: require('current_theme')

vim.cmd.colorscheme("greenhill")

-- Optional: Inject global variables if your theme uses them
vim.g.chameleon_theme = "greenhill"