-- Generated by Chameleon for theme: SANXZ4
-- Require this file in your init.lua: require('current_theme')

vim.cmd.colorscheme("sanxz4")

-- Optional: Inject global variables if your theme uses them
vim.g.chameleon_theme = "sanxz4"