# Generated by Chameleon for theme: SANXZ5
# Source this file in your .zshrc

# UI Colors
export COLOR_BACKGROUND='#050010'
export COLOR_FOREGROUND='#E0C0FF'

# Palette Variables
export c00_black='#050010'
export c01_red='#FF00FF'
export c02_green='#FFFF55'
export c03_yellow='#9900FF'
export c04_blue='#00FFFF'
export c05_violet='#DD55FF'
export c06_cyan='#FF8800'
export c07_white='#E0C0FF'
export c08_br_black='#330055'
export c09_br_red='#B000FF'
export c10_br_green='#AAFF00'
export c11_br_yellow='#FF00AA'
export c12_br_blue='#FFCC00'
export c13_br_violet='#6600FF'
export c14_br_cyan='#00AAAA'
export c15_br_white='#FFFFFF'

# --- LS_COLORS Dynamic Generation ---
# Automatically maps palette colors to file types

export LS_COLORS="di=1;38;2;0;255;255:"  # Directory
LS_COLORS+="ln=38;2;255;136;0:"         # Symlink
LS_COLORS+="ex=1;38;2;255;255;85:"       # Executable
LS_COLORS+="*.zip=38;2;255;0;255:*.tar=38;2;255;0;255:*.gz=38;2;255;0;255:" # Archives
LS_COLORS+="*.jpg=38;2;221;85;255:*.png=38;2;221;85;255:*.mp4=38;2;221;85;255:*.mp3=38;2;221;85;255:" # Media
LS_COLORS+="*.py=38;2;255;136;0:*.js=38;2;255;136;0:*.c=38;2;255;136;0:" # Code
LS_COLORS+="*.txt=38;2;224;192;255:*.md=38;2;224;192;255:*.cfg=38;2;224;192;255:" # Docs

# Apply to Zsh completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"