# Generated by Chameleon for theme: SANXZ4
# Source this file in your .zshrc

# UI Colors
export COLOR_BACKGROUND='#110011'
export COLOR_FOREGROUND='#DD55FF'

# Palette Variables (Matching your existing naming convention if possible)
export c00_black='#000000'
export c01_red='#FF5555'
export c02_green='#55FF55'
export c03_yellow='#FFFF55'
export c04_blue='#5555FF'
export c05_violet='#DD55FF'
export c06_cyan='#55DDFF'
export c07_white='#FFFFFF'
export c08_br_black='#440044'
export c09_br_red='#FF5555'
export c10_br_green='#55FF55'
export c11_br_yellow='#FFFF55'
export c12_br_blue='#5555FF'
export c13_br_violet='#DD55FF'
export c14_br_cyan='#55DDFF'
export c15_br_white='#FFFFFF'