# Generated by Chameleon for theme: SANXZ Warm/Cool
# Source this file in your .zshrc

# UI Colors
export COLOR_BACKGROUND='#000008'
export COLOR_FOREGROUND='#FF5555'

# Palette Variables
export c00_black='#000000'
export c01_red='#FF0000'
export c02_green='#00FF00'
export c03_yellow='#FFFF00'
export c04_blue='#0000FF'
export c05_violet='#8000FF'
export c06_cyan='#00FFFF'
export c07_white='#FFFFFF'
export c08_br_black='#222222'
export c09_br_red='#FF5555'
export c10_br_green='#55FF55'
export c11_br_yellow='#FFFF77'
export c12_br_blue='#5555FF'
export c13_br_violet='#AA55FF'
export c14_br_cyan='#55FFFF'
export c15_br_white='#FFFFFF'

# --- LS_COLORS Dynamic Generation ---
# Automatically maps palette colors to file types

export LS_COLORS="di=1;38;2;0;0;255:"  # Directory
LS_COLORS+="ln=38;2;0;255;255:"         # Symlink
LS_COLORS+="ex=1;38;2;0;255;0:"       # Executable
LS_COLORS+="*.zip=38;2;255;0;0:*.tar=38;2;255;0;0:*.gz=38;2;255;0;0:" # Archives
LS_COLORS+="*.jpg=38;2;128;0;255:*.png=38;2;128;0;255:*.mp4=38;2;128;0;255:*.mp3=38;2;128;0;255:" # Media
LS_COLORS+="*.py=38;2;0;255;255:*.js=38;2;0;255;255:*.c=38;2;0;255;255:" # Code
LS_COLORS+="*.txt=38;2;255;255;255:*.md=38;2;255;255;255:*.cfg=38;2;255;255;255:" # Docs

# Apply to Zsh completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"